development:
  adapter: postgresql
  encoding: unicode
  database: recipe_development
  pool: 5
  username: postgres
  password: turn0ffth3l1ghts
  host: localhost

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: recipe_test
  pool: 5
  username: postgres
  password: turn0ffth3l1ghts
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: recipe_production
  pool: 5
  username: postgres
  password: turn0ffth3l1ghts
