development:
  adapter: postgresql
  encoding: unicode
  database: recipe_development
  pool: 5
  username: postgres
  password: turn0ffth3l1ghts
  host: localhost

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
